services:
  react-app:
    container_name: mems-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    networks:
      mems-network:
        ipv4_address: 192.168.1.2
    ports:
      - "3000:3000"
    stdin_open: true 
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: 
      sh -c "
        yarn
      "
networks:
  mems-network:
    external: true
